package com.example.http_manage_biz.greedao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.http_manage_biz.vo.MenuInfo;

import com.example.http_manage_biz.greedao.MenuInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig menuInfoDaoConfig;

    private final MenuInfoDao menuInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        menuInfoDaoConfig = daoConfigMap.get(MenuInfoDao.class).clone();
        menuInfoDaoConfig.initIdentityScope(type);

        menuInfoDao = new MenuInfoDao(menuInfoDaoConfig, this);

        registerDao(MenuInfo.class, menuInfoDao);
    }
    
    public void clear() {
        menuInfoDaoConfig.getIdentityScope().clear();
    }

    public MenuInfoDao getMenuInfoDao() {
        return menuInfoDao;
    }

}
